name: Deploy to Remote
on:
  push:
    branches:
      - main

jobs:
  deployToRemote:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use lts Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2
      - name: Install & Lint
        run: |
          npm install -g pnpm
          pnpm install
          pnpm lint
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/powerboard:${{github.run_number}}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            # 停止旧版容器
            docker stop $(docker ps --filter name=powerboard -q)
            # 删除旧版容器
            docker rm -f $(docker ps -a --filter name=powerboard -q)
            # 删除旧版镜像
            docker rmi -f $(docker images ${{ secrets.DOCKERHUB_USERNAME }}/powerboard -q)
            # 登陆镜像服务器
            docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
            # 拉取最新latest版本镜像
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/powerboard:${{github.run_number}}
            # 运行最新latest版本镜像
            docker run --name powerboard -d  -p 4321:80 ${{ secrets.DOCKERHUB_USERNAME }}/powerboard:${{github.run_number}}
